### ISSUE TITLE
Factorio VCC: Game client connect; immediate desync

### ISSUE THREAD

**Issue by ThePowerTool** [mk-fg/games#8] opened 2023-01-27 18:28 UTC
Hi,

I *love* the Vehicle Cruise Control mod for Factorio.  It used to be a part of every game I played in Factorio.

For some time now I have noticed (across multiple systems as this is happening to others with whom I play) the VCC mod now causes desync immediately after connecting.

I know the games projects you have posted, here, are something infrequently updated.  This isn't an urgent request--but I do love the mod and would like to be able to use it, again.

And now, at the risk of pushing my luck, a feature request:  Might it be possible to allow for advance mouse-click selection of a destination? :)

Thank you very much!

**Comment by mk-fg** [comment] 2023-01-27 19:04
Oh, I know what it likely is - these two lines:
https://github.com/mk-fg/games/blob/master/factorio/Vehicle_Cruise_Control/control.lua#L1-L2

That's state that is not synced between players, and if they're ever non-empty when new player joins - guaranteed desync.
Should be easy to fix though, by putting those into factorio "global" table instead, which is exactly for this kind of state and always synced on join and saved between save/load.

Will fix in a bit, should be just a small patch, thanks.
I've never played factorio multiplayer, so pretty much only notice this kind of stuff when someone brings it up.
(also tbf haven't played factorio in like 2y too, but will maybe get back to it when they make that expansion)

**Comment by mk-fg** [comment] 2023-01-27 19:10
> And now, at the risk of pushing my luck, a feature request: Might it be possible to allow for advance mouse-click selection of a destination? :)

That's trickier, and probably best be implemented in a separate mod.

Algorithm will presumably be something like this:

- Accelerate to some low speed, hold it
- Hold turn until pointing at destination
- Hold acceleration until distance to destination goes from decreasing to increasing

Which shouldn't be hard to implement, but doesn't really have much overlap internally with this simple "press key to set accelerating/braking state" mod.

**Comment by ThePowerTool** [comment] 2023-01-27 20:22
Oops... I buried the lead.  I should have been more specific.  I use the hover-car and helicopter mods.  Would it be simpler to implement given no "ground issues"?  Although I can see how this could also apply to tanks but should come with a warning from the surgeon general that auto-pilot can be hazardous to the health of some vehicles :D

And a speed slider? <--I completely forgot why I had asked:  I enjoy using the hovercar for personal-roboport-robot-installs of blueprints and a speed slider would be very handy!

**Comment by ThePowerTool** [comment] 2023-01-27 20:23
desync: Thank you, again, in-advance!

**Comment by mk-fg** [comment] 2023-01-27 21:38
> I use the hover-car and helicopter mods. Would it be simpler to implement given no "ground issues"?

Not really, should be same process as described above, as I didn't take any pathfinding there into account for simplicity.
And yeah, presumably player can be trusted to do whatever pathfinding they want with clicks manually, once they understand that it only sets the direction + destination and does nothing beyond that.

I wonder if maybe with hovercar and especially helicopter mods, better prototype for such vehicles would've been a spidertron instead of a car/tank, as it supports such clicking interface and might be better suited to this kind of terrain-ignoring thing.
Haven't ever tried building spidertron in factorio myself though, and don't have first-hand knowledge of how they control, so can easily be wrong about that.
Since I've seen these mods on the portal, they were likely made way before spidertron was added, so it maybe wasn't an option for those, at least if it's same couple of old popular mods that I'm thinking about.

**Comment by mk-fg** [comment] 2023-01-30 22:31
Should be fixed in 3b88d75 / 0.0.8.
Thanks again for reporting it.

**Closed as completed by mk-fg** 2023-01-30 22:31 UTC

**Comment by mk-fg** [comment] 2023-01-30 22:33
Or well, I think it should be fixed, due removal of that obvious mp-unfriendly code pattern, but haven't tested running it in MP, so hopefully there aren't any other issues (which seems likely, given how code here is kinda trivial).

**Comment by ThePowerTool** [comment] 2023-02-02 08:43
I can now confirm this fix.

I just participated in an ongoing, multiplayer game.  This session was, at-least, 4 hours.  With Vehicle_Cruise_Control_0.0.8 loaded everything ran smoothly.

This session was with a total of 2 players.

FYI & FWIW I have never seen the desync in a single-player game--I don't think it's possible for a single player in a single-player-game to desync.  But I'm not an expert :-)

I love this mod!  It is amazingly useful especially on large maps and in games that quickly lead to large maps (e.g. Space Exploration) allowing for multi-tasking.

*Note*: It also makes for TONS of fun if you forget you set the cruise control on a map full of biters (roflmao).

Thank you very much!!!

**Comment by mk-fg** [comment] 2023-02-02 19:47
> FYI & FWIW I have never seen the desync in a single-player game--I don't think it's possible for a single player in a single-player-game to desync. But I'm not an expert :-)

Yeah, this kind of desynchronization only happens in multiplayer game with an actual multiple players present.

I think game just periodically runs sanity-check on their internal game-state and errors-out if it is detected to be not exactly equal, as that'd mean that players see different things in their game, which is obviously broken and is likely to get more-and-more out of sync pretty quickly (as running same code/logic in each player's game will produce more such desyncs, starting from the original one).
Kinda like if you don't replicate one move when playing chess remotely (e.g. E2-E4), game won't make any sense past that point.

Wish there was some easy in-game "randomly run simulated parallel game-states at arbitrary times" option for modders, to easily detect such issues when playing SP game with the mods, and simply notify that there is a problem.

**Comment by ThePowerTool** [comment] 2023-02-03 04:49
> Wish there was some easy in-game "randomly run simulated parallel game-states at arbitrary times" option for modders, to easily detect such issues when playing SP game with the mods, and simply notify that there is a problem.

Well, from my experience in this specific situation, I ran a headless server, connected (just me) as a single player in a multi-player game hosted on a remote server and immediately saw the desync.

Just a thought :)  I don't think I would have thought of that if I hadn't actually seen it.

Also, I remember reading-up on Factorio and it's a game built to step sequentially--there's a word they used to describe that but I'm drawing a blank atm.  All games in a multiplayer scenario have to "step in sync."  This also creates challenges for taking advantages of multiple cores and threads (from a coding perspective).

**Comment by mk-fg** [comment] 2023-02-03 08:45
Yeah, I think "lockstep" is the usual name for this kind of parallel systems, where each player/client/instance runs same exact code from same exact initial state and expected to always get same new state (as other clients) as a result of that.

Interesting that it's reproducible on a dedicated server with one player - guess server itself runs that kind of machine for the world simulation to move through game-time faithfully even when no players are connected, and desync happens with that.
That indeed seem to be simple way to detect such issues, without needing to run multiple factorio instances in parallel at different times, as I thought it should require.
